/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.uv.hibernatecrud.gui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author asunawesker
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        mnCourseCreate = new javax.swing.JMenu();
        jMenuDepartamento = new javax.swing.JMenuItem();
        mnEmpleadoCreate = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnDepartamentoSearch = new javax.swing.JMenuItem();
        mnEmpleadoSearch = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnDepartamentoUpdate = new javax.swing.JMenuItem();
        mnEmpleadoUpdate = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(612, 450));

        jDesktopPane1.setToolTipText("");
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(700, 500));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(700, 500));
        jDesktopPane1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Inicio");

        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        mnCourseCreate.setText("Agregar");

        jMenuDepartamento.setText("Departamento");
        jMenuDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDepartamentoActionPerformed(evt);
            }
        });
        mnCourseCreate.add(jMenuDepartamento);

        mnEmpleadoCreate.setText("Empleado");
        mnEmpleadoCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEmpleadoCreateActionPerformed(evt);
            }
        });
        mnCourseCreate.add(mnEmpleadoCreate);

        jMenuBar1.add(mnCourseCreate);

        jMenu3.setText("Buscar");

        mnDepartamentoSearch.setText("Departamento");
        mnDepartamentoSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDepartamentoSearchActionPerformed(evt);
            }
        });
        jMenu3.add(mnDepartamentoSearch);

        mnEmpleadoSearch.setText("Profesor");
        mnEmpleadoSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEmpleadoSearchActionPerformed(evt);
            }
        });
        jMenu3.add(mnEmpleadoSearch);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Actualizar");

        mnDepartamentoUpdate.setText("Departamento");
        mnDepartamentoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDepartamentoUpdateActionPerformed(evt);
            }
        });
        jMenu4.add(mnDepartamentoUpdate);

        mnEmpleadoUpdate.setText("Profesor");
        mnEmpleadoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEmpleadoUpdateActionPerformed(evt);
            }
        });
        jMenu4.add(mnEmpleadoUpdate);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void jMenuDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDepartamentoActionPerformed
        // TODO add your handling code here:
        DepartmentCreate course; 
        try {          
            course = new DepartmentCreate();
            jDesktopPane1.add(course);
            course.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuDepartamentoActionPerformed

    private void jMenuProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProfessorActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_jMenuProfessorActionPerformed

    private void mnDepartamentoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDepartamentoUpdateActionPerformed
        // TODO add your handling code here:
        DepartmentUpdate course;
        
        try {
            course = new DepartmentUpdate();
            jDesktopPane1.add(course);
            course.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnDepartamentoUpdateActionPerformed

    private void mnDepartamentoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDepartamentoSearchActionPerformed
        // TODO add your handling code here:
        DepartmentSearch course;
        
        try {
            course = new DepartmentSearch();
            jDesktopPane1.add(course);
            course.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnDepartamentoSearchActionPerformed

    private void mnEmpleadoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEmpleadoSearchActionPerformed
        // TODO add your handling code here:
        EmployeeSearch professor;
        
        try {
            professor = new EmployeeSearch();
            jDesktopPane1.add(professor);
            professor.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_mnEmpleadoSearchActionPerformed

    private void mnEmpleadoCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEmpleadoCreateActionPerformed
        // TODO add your handling code here:
        EmployeeCreate professor;
        
        try {
            professor = new EmployeeCreate();
            jDesktopPane1.add(professor);
            professor.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_mnEmpleadoCreateActionPerformed

    private void mnEmpleadoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEmpleadoUpdateActionPerformed
        // TODO add your handling code here:
        EmployeeUpdate professor;
        
        try {
            professor = new EmployeeUpdate();
            jDesktopPane1.add(professor);
            professor.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnEmpleadoUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exit;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDepartamento;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mnCourseCreate;
    private javax.swing.JMenuItem mnDepartamentoSearch;
    private javax.swing.JMenuItem mnDepartamentoUpdate;
    private javax.swing.JMenuItem mnEmpleadoCreate;
    private javax.swing.JMenuItem mnEmpleadoSearch;
    private javax.swing.JMenuItem mnEmpleadoUpdate;
    // End of variables declaration//GEN-END:variables
}
